application: cc-nanny
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin  
  
- url: /admin
  script: admin.py
  login: admin
  
- url: /admin/.*
  script: admin.py
  login: admin
  
- url: /test-secure-page
  script: main.py
  secure: always

- url: .*
  script: main.py
